#!/bin/bash

TITLE="Shitty Manual"
DATE=$(date +'%Y-%m-%d')
VERSION=$2
POD=$1

SECTION=${POD%.pod}; SECTION=${SECTION##*.}
NAME=${POD%%.*}; NAME=${NAME##*/}; NAME=$(echo $NAME | dd conv=ucase 2>/dev/null)

echo >&2 "[POD] $POD -> $NAME($SECTION) v$VERSION"
pod2man --center "$TITLE" --date "$DATE" --release "Shitty v$VERSION" --name "$NAME" --section "$SECTION" $POD
rm -f man/*.tmp
